blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Ibinola/soroban-dev-console/discussions
    about: Please ask questions or start discussions in GitHub Discussions instead of opening an issue.
